server:
  port: 8080
  servlet:    encoding:      force: true
      charset: UTF-8
#数据库配置
spring:
  config:
#    location: classpath:configs/config.properties
  #热部署配置 仅开发环境用
  devtools:
    restart:
      enabled: true
#      additional-paths: resources/**,static/**,basepages/**
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://10.5.1.11:3306/test?useSSL=false&serverTimezone=GMT%2B8"
    username: test
    password: test
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: "SELECT 1"
  redis:
    host: 10.5.1.12
    password: redisadmin
    port: 6379
    timeout: 10000
    database: 6
    sentinel:      master: mymaster
      nodes:      - 10.5.1.12:26379
      - 10.5.1.12:26380
logging:  file:    max-size: 10MB    name: showboard.log
    path: d:/temp
    max-history: 7    
      